name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build Maven
        run: mvn -B package --file pom.xml
      - name: Run Test
        run: mvn -Dtest=CreateUserTest#createUser test
      - name: Run Test
        run: mvn -Dtest=CreateUserContractTest#createUserContract test

